'use strict';
const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const SERVICE=0xFFE6,WRITE=0xFFE1,NOTIFY=0xFFE2,RASTER_W=384,ROW_BYTES=48,MAX_H=2048,FEED_LINES=40;
const photo={image:{source:null,raster:null,height:0},camera:{source:null,raster:null,height:0}};let textRaster=null,textHeight=0,textTimer=0,qrRaster=null,qrHeight=0,qrTimer=0;
function log(...a){const s=a.map(v=>typeof v==='string'?v:JSON.stringify(v)).join(' '),e=$('#debugLog');if(e){e.textContent+=(e.textContent?'\n':'')+new Date().toLocaleTimeString()+' '+s;e.scrollTop=e.scrollHeight}console.log(...a)}
function setState(sel,msg,error=false){const e=$(sel);if(!e)return;e.textContent=msg;e.classList.toggle('err',error);e.classList.toggle('ok',!error&&!!msg)}
function normalizeMac(s){if(!s)return'';const h=String(s).replace(/[^0-9a-f]/gi,'').toUpperCase();if(h.length!==12)return'';return h.match(/../g).join(':')}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));const v=$('#view-'+name);if(!v)return;v.classList.add('active');const b=document.querySelector(`#nav button[data-view="${name}"]`);if(b)b.classList.add('active')}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
class BusyError extends Error{constructor(m='Printing in progress'){super(m);this.name='BusyError'}}
class WebBluetoothTransport{
 constructor(targetMac=''){this.targetMac=normalizeMac(targetMac);this.device=null;this.server=null;this.writeChar=null;this.notifyChar=null;this.actualMac='';this.state='idle';this.error='';this.printing=false;this.connecting=false;this.waiters=[];this.flow={finished:false,hold:false,cooldown:false,lost:null};this.onState=()=>{};this._boundNotify=e=>this._onNotify(e);this._boundDisconnect=()=>this._onDisconnect()}
 _set(state,error=''){this.state=state;this.error=error;this.connecting=state==='connecting';this.printing=state==='printing';this.onState(this.status())}
 status(){return{state:this.state,error:this.error,targetMac:this.targetMac,actualMac:this.actualMac,name:this.device?.name||'',connected:!!this.device?.gatt?.connected,ready:this.state==='ready'||this.state==='printing',printing:this.printing}}
 _onDisconnect(){log('Bluetooth disconnected');this.server=this.writeChar=this.notifyChar=null;this.actualMac='';this._rejectWaiters(new Error('Printer disconnected'));this._set('idle')}
 _rejectWaiters(err){for(const w of this.waiters.splice(0)){clearTimeout(w.timer);w.reject(err)}}
 _wait(type,timeout=4000){return new Promise((resolve,reject)=>{const w={type,resolve:v=>{clearTimeout(w.timer);resolve(v)},reject};w.timer=setTimeout(()=>{this.waiters=this.waiters.filter(x=>x!==w);reject(new Error(type+' timeout'))},timeout);this.waiters.push(w)})}
 _emit(type,data={}){const i=this.waiters.findIndex(w=>w.type===type);if(i>=0){const [w]=this.waiters.splice(i,1);w.resolve(data)}}
 _onNotify(ev){const d=new Uint8Array(ev.target.value.buffer,ev.target.value.byteOffset,ev.target.value.byteLength);if(d.length<2||d[0]!==0x5A)return;switch(d[1]){case 0x01:{if(d.length>=10){const m=Array.from(d.slice(4,10),x=>x.toString(16).padStart(2,'0').toUpperCase()).join(':');this.actualMac=m;this._emit('hello',{mac:m,raw:d.slice(4,10)})}break}case 0x05:if(d.length>=4){this.flow.lost=(d[2]<<8)|d[3];this.flow.hold=false}break;case 0x06:this.flow.finished=true;this.flow.hold=false;this._emit('finished');break;case 0x07:this.flow.cooldown=true;break;case 0x08:this.flow.hold=true;break;case 0x0A:this._emit('authChallenge');break;case 0x0B:this._emit('authResult',{ok:d.length>=3&&d[2]===1});break;default:break}}
 async _write(data){if(!this.writeChar)throw new Error('Printer is not connected');let last;for(let i=0;i<=50;i++){try{if(typeof this.writeChar.writeValueWithoutResponse==='function')await this.writeChar.writeValueWithoutResponse(data);else await this.writeChar.writeValue(data);return}catch(e){last=e;if(!this.device?.gatt?.connected)throw e;if(i===50)break;await sleep(10)}}throw last||new Error('BLE write failed')}
 async _hello(){const wait=this._wait('hello');await this._write(Uint8Array.of(0x5A,0x01,0,0,0,0,0,0,0,0,0,0));return wait}
 async _connectDevice(device){this._set('connecting');this.device=device;device.removeEventListener('gattserverdisconnected',this._boundDisconnect);device.addEventListener('gattserverdisconnected',this._boundDisconnect);try{this.server=await device.gatt.connect();const svc=await this.server.getPrimaryService(SERVICE);this.writeChar=await svc.getCharacteristic(WRITE);this.notifyChar=await svc.getCharacteristic(NOTIFY);await this.notifyChar.startNotifications();this.notifyChar.removeEventListener('characteristicvaluechanged',this._boundNotify);this.notifyChar.addEventListener('characteristicvaluechanged',this._boundNotify);const hello=await this._hello();if(this.targetMac&&hello.mac!==this.targetMac){device.gatt.disconnect();throw new Error(`Selected printer MAC ${hello.mac} does not match target ${this.targetMac}`)}this.actualMac=hello.mac;this._set('ready');log('Printer ready',device.name||'(unnamed)',hello.mac);return true}catch(e){this.error=e.message||String(e);if(device.gatt?.connected)device.gatt.disconnect();this._set('error',this.error);throw e}}
 async connectWithChooser(){if(!navigator.bluetooth)throw new Error('Web Bluetooth is not available in this browser');const d=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[SERVICE]});return this._connectDevice(d)}
 async tryAutoConnect(){if(!this.targetMac||!navigator.bluetooth?.getDevices)return false;let devices=[];try{devices=await navigator.bluetooth.getDevices()}catch(e){log('getDevices failed',e.message);return false}for(const d of devices){try{log('Trying previously authorized device',d.name||d.id);await this._connectDevice(d);if(this.actualMac===this.targetMac)return true}catch(e){log('Auto reconnect candidate rejected',e.message)}}if(this.state==='error')this._set('idle');return false}
 disconnect(){if(this.device?.gatt?.connected)this.device.gatt.disconnect();else this._onDisconnect()}
 _crc16(data){let crc=0;for(const x of data){crc^=x<<8;for(let i=0;i<8;i++)crc=(crc&0x8000)?((crc<<1)^0x1021)&0xFFFF:(crc<<1)&0xFFFF}return crc}
 _authResponse(ch,mac){const out=new Uint8Array(12);out[0]=0x5A;out[1]=0x0B;for(let i=0;i<10;i++){const inb=Uint8Array.of(ch[i],...mac),crc=this._crc16(inb);out[i+2]=crc>>8}return out}
 _control(count,end){return Uint8Array.of(0x5A,0x04,(count>>8)&255,count&255,end?1:0,0)}
 _packet(index,raster,height){const p=new Uint8Array(100);p[0]=0x55;p[1]=(index>>8)&255;p[2]=index&255;const y0=index*2,y1=y0+1;if(y0<height)p.set(raster.subarray(y0*ROW_BYTES,(y0+1)*ROW_BYTES),3);if(y1<height)p.set(raster.subarray(y1*ROW_BYTES,(y1+1)*ROW_BYTES),51);return p}
 async _printInner(raster,height){if(this.state!=='ready')throw new Error('Printer is not ready');if(!raster||height<1||height>MAX_H||raster.length!==height*ROW_BYTES)throw new Error('Invalid RasterJob');this._set('printing');this.flow={finished:false,hold:false,cooldown:false,lost:null};try{const helloWait=this._wait('hello');await this._write(Uint8Array.of(0x5A,0x01,0,0,0,0,0,0,0,0,0,0));const hello=await helloWait;const mac=hello.raw;const challenge=crypto.getRandomValues(new Uint8Array(10)),challengeWait=this._wait('authChallenge');const cp=new Uint8Array(12);cp[0]=0x5A;cp[1]=0x0A;cp.set(challenge,2);await this._write(cp);await challengeWait;const authWait=this._wait('authResult');await this._write(this._authResponse(challenge,mac));const auth=await authWait;if(!auth.ok)throw new Error('Printer authentication rejected');await this._write(Uint8Array.of(0x5A,0x0C,3));const count=Math.ceil((height+FEED_LINES)/2);await this._write(this._control(count,false));let idx=0,lastProgress=Date.now();while(idx<count){if(this.flow.finished)break;if(Date.now()-lastProgress>60000)throw new Error('Print stalled');if(this.flow.cooldown){this.flow.cooldown=false;await sleep(100);continue}if(this.flow.lost!==null){idx=Math.max(0,this.flow.lost-1);this.flow.lost=null;lastProgress=Date.now();continue}if(this.flow.hold){await sleep(20);continue}await this._write(this._packet(idx,raster,height));idx++;lastProgress=Date.now();if(idx<count)await sleep(20)}const deadline=Date.now()+10000;while(!this.flow.finished&&Date.now()<deadline)await sleep(20);if(!this.flow.finished)throw new Error('Finish timeout');await this._write(this._control(count,true));this._set('ready');return true}catch(e){this._set(this.device?.gatt?.connected?'ready':'error',e.message||String(e));throw e}}
 async printRaster(raster,height){const lockName='thermal-bridge-printer-'+(this.actualMac||this.targetMac||this.device?.id||'default');if(navigator.locks?.request){let acquired=false,result;await navigator.locks.request(lockName,{ifAvailable:true},async lock=>{if(!lock)return;acquired=true;result=await this._printInner(raster,height)});if(!acquired)throw new BusyError('Another tab is printing');return result}if(this.printing)throw new BusyError();return this._printInner(raster,height)}
}
const params=new URLSearchParams(location.search),targetMac=normalizeMac(params.get('mac')||'');const transport=new WebBluetoothTransport(targetMac);
function transportChanged(s){const badge=$('#connBadge'),busy=$('#busyBanner'),target=$('#targetMac'),actual=$('#actualMac'),name=$('#deviceName'),state=$('#printerState'),connect=$('#connectPrinter'),disconnect=$('#disconnectPrinter');if(badge)badge.textContent='Printer: '+(s.printing?'printing':s.ready?'connected':s.state);if(busy)busy.hidden=!s.printing;if(target)target.textContent=s.targetMac||'(not specified)';if(actual)actual.textContent=s.actualMac||'—';if(name)name.textContent=s.name||'—';if(state)state.textContent=s.error?`${s.state}: ${s.error}`:s.state;if(connect)connect.disabled=s.connecting||s.ready||s.printing;if(disconnect)disconnect.disabled=!s.connected||s.printing;refreshPrintButtons()}transport.onState=transportChanged;transportChanged(transport.status());
function canPrint(){return transport.status().ready&&!transport.status().printing}function refreshPrintButtons(){const ok=canPrint();$('#printText').disabled=!ok||!textRaster;$('#printImage').disabled=!ok||!photo.image.raster;$('#printCamera').disabled=!ok||!photo.camera.raster;$('#printQr').disabled=!ok||!qrRaster;const t=$('#testPattern');if(t)t.disabled=!ok}
$('#connectPrinter').onclick=async()=>{setState('#printerMsg','Opening Bluetooth device chooser…');try{await transport.connectWithChooser();setState('#printerMsg','Connected.')}catch(e){setState('#printerMsg',e.message||String(e),true)}};$('#disconnectPrinter').onclick=()=>transport.disconnect();{const b=$('#clearLog');if(b)b.onclick=()=>{const e=$('#debugLog');if(e)e.textContent=''}};
function grayOf(r,g,b){return .2126*r+.7152*g+.0722*b}function setBit(buf,y,x){buf[y*ROW_BYTES+(x>>3)]|=0x80>>(x&7)}
function canvasToRaster(c,mode='threshold',t0=160){const ctx=c.getContext('2d',{willReadFrequently:true}),w=RASTER_W,h=c.height,img=ctx.getImageData(0,0,w,h),n=w*h,g=new Float32Array(n);for(let i=0;i<n;i++)g[i]=grayOf(img.data[i*4],img.data[i*4+1],img.data[i*4+2]);const raster=new Uint8Array(h*ROW_BYTES);if(mode==='floyd'){for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,o=g[i],b=o<t0,nv=b?0:255;if(b)setBit(raster,y,x);const e=o-nv;if(x+1<w)g[i+1]+=e*7/16;if(y+1<h){if(x)g[i+w-1]+=e*3/16;g[i+w]+=e*5/16;if(x+1<w)g[i+w+1]+=e/16}}}else if(mode==='bayer'){const m=[0,8,2,10,12,4,14,6,3,11,1,9,15,7,13,5];for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(g[y*w+x]+(t0-128)<(m[(y&3)*4+(x&3)]+.5)*16)setBit(raster,y,x)}else{for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(g[y*w+x]<t0)setBit(raster,y,x)}for(let y=0;y<h;y++)for(let x=0;x<w;x++){const b=raster[y*ROW_BYTES+(x>>3)]&(0x80>>(x&7)),i=(y*w+x)*4,v=b?0:255;img.data[i]=img.data[i+1]=img.data[i+2]=v;img.data[i+3]=255}ctx.putImageData(img,0,0);return raster}
async function submitRaster(raster,height,stateSel){if(!raster)return;setState(stateSel,'Printing…');refreshPrintButtons();try{await transport.printRaster(raster,height);setState(stateSel,'Done.')}catch(e){setState(stateSel,e instanceof BusyError?'印刷中です。完了までお待ちください。':'Print failed: '+(e.message||e),true)}refreshPrintButtons()}
function loadImageFile(file,kind){if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);photo[kind].source=img;renderPhoto(kind)};img.onerror=()=>{URL.revokeObjectURL(url);setState('#'+kind+'State','Could not read image.',true)};img.src=url}
function renderPhoto(kind){const st=photo[kind],img=st.source;if(!img)return;const cap=Number($('#'+kind+'MaxHeight').value),h=Math.max(1,Math.min(cap,Math.round(img.naturalHeight*RASTER_W/img.naturalWidth))),c=$('#'+kind+'Preview'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=RASTER_W;c.height=h;ctx.fillStyle='#fff';ctx.fillRect(0,0,RASTER_W,h);ctx.drawImage(img,0,0,RASTER_W,h);st.raster=canvasToRaster(c,$('#'+kind+'Dither').value,Number($('#'+kind+'Threshold').value));st.height=h;setState('#'+kind+'State',`${RASTER_W} × ${h}, ${st.raster.byteLength} bytes`);refreshPrintButtons()}
for(const kind of ['image','camera']){$('#'+kind+'File').onchange=()=>loadImageFile($('#'+kind+'File').files[0],kind);$('#'+kind+'Dither').onchange=()=>renderPhoto(kind);$('#'+kind+'MaxHeight').onchange=()=>renderPhoto(kind);$('#'+kind+'Threshold').oninput=()=>{$('#'+kind+'ThresholdValue').textContent=$('#'+kind+'Threshold').value;renderPhoto(kind)};$('#print'+(kind==='image'?'Image':'Camera')).onclick=()=>submitRaster(photo[kind].raster,photo[kind].height,'#'+kind+'State')}
function wrapChars(ctx,text,maxWidth){const lines=[];for(const para of text.replace(/\r/g,'').split('\n')){if(para===''){lines.push('');continue}let line='';for(const ch of Array.from(para)){const t=line+ch;if(line&&ctx.measureText(t).width>maxWidth){lines.push(line);line=ch}else line=t}if(line)lines.push(line)}return lines}
function renderText(){clearTimeout(textTimer);const text=$('#textInput').value,c=$('#textPreview'),ctx=c.getContext('2d',{willReadFrequently:true}),size=Number($('#textSize').value),bold=$('#textBold').checked,align=$('#textAlign').value,lineMul=Number($('#textLine').value),margin=12;ctx.font=`${bold?'700 ':'400 '}${size}px sans-serif`;const lines=wrapChars(ctx,text,RASTER_W-margin*2),lh=Math.ceil(size*lineMul),h=Math.max(1,Math.min(MAX_H,margin*2+Math.max(1,lines.length)*lh));c.width=RASTER_W;c.height=h;ctx.fillStyle='#fff';ctx.fillRect(0,0,RASTER_W,h);ctx.fillStyle='#000';ctx.font=`${bold?'700 ':'400 '}${size}px sans-serif`;ctx.textBaseline='top';ctx.textAlign=align;const x=align==='left'?margin:(align==='right'?RASTER_W-margin:RASTER_W/2);let y=margin;for(const line of lines){if(y+lh>h)break;ctx.fillText(line,x,y,RASTER_W-margin*2);y+=lh}textRaster=text.trim()?canvasToRaster(c,'threshold',210):null;textHeight=h;setState('#textState',textRaster?`${RASTER_W} × ${h}, ${textRaster.byteLength} bytes`:'');refreshPrintButtons()}
function scheduleText(){clearTimeout(textTimer);textTimer=setTimeout(renderText,120)}for(const id of ['textInput','textSize','textBold','textAlign','textLine'])$('#'+id).addEventListener(id==='textInput'?'input':'change',scheduleText);$('#printText').onclick=()=>submitRaster(textRaster,textHeight,'#textState');
function renderQr(){clearTimeout(qrTimer);const text=$('#qrInput').value,n=new TextEncoder().encode(text).length;$('#qrCount').textContent=`${n} / 768 bytes`;qrRaster=null;qrHeight=0;if(!text){const c=$('#qrPreview');c.width=RASTER_W;c.height=1;setState('#qrState','');refreshPrintButtons();return}if(n>768){setState('#qrState','QR data exceeds 768 UTF-8 bytes.',true);refreshPrintButtons();return}try{const q=QrLite.encode(text),mods=q.modules,count=mods.length,quiet=4,maxQr=336,scale=Math.max(1,Math.floor(maxQr/(count+quiet*2))),qrPx=(count+quiet*2)*scale,margin=12,gap=10,fontSize=18,lineHeight=24,measure=document.createElement('canvas').getContext('2d');measure.font=`400 ${fontSize}px sans-serif`;const lines=wrapChars(measure,text,RASTER_W-margin*2),textBlock=Math.max(lineHeight,lines.length*lineHeight),h=Math.min(MAX_H,qrPx+gap+margin+textBlock+margin),c=$('#qrPreview'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=RASTER_W;c.height=h;ctx.fillStyle='#fff';ctx.fillRect(0,0,RASTER_W,h);const x0=Math.floor((RASTER_W-qrPx)/2)+quiet*scale,y0=quiet*scale;ctx.fillStyle='#000';for(let y=0;y<count;y++)for(let x=0;x<count;x++)if(mods[y][x])ctx.fillRect(x0+x*scale,y0+y*scale,scale,scale);ctx.font=`400 ${fontSize}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='top';let ty=qrPx+gap+margin;for(const line of lines){if(ty+lineHeight>h-margin)break;ctx.fillText(line,RASTER_W/2,ty,RASTER_W-margin*2);ty+=lineHeight}qrRaster=canvasToRaster(c,'threshold',210);qrHeight=h;setState('#qrState',`Version ${q.version}, preview ${RASTER_W} × ${h}, ${qrRaster.byteLength} bytes`)}catch(e){setState('#qrState','QR render failed: '+(e.message||e),true)}refreshPrintButtons()}
function scheduleQr(){clearTimeout(qrTimer);qrTimer=setTimeout(renderQr,120)}$('#qrInput').oninput=scheduleQr;$('#printQr').onclick=()=>submitRaster(qrRaster,qrHeight,'#qrState');
function testPattern(){const h=64,r=new Uint8Array(h*ROW_BYTES);for(let y=0;y<h;y++)for(let x=0;x<RASTER_W;x++){let black=y<2||y>=h-2||x<2||x>=RASTER_W-2;if(Math.floor(x/24)===Math.floor(y/4)||Math.floor((RASTER_W-1-x)/24)===Math.floor(y/4))black=true;if(y>=28&&y<36&&Math.floor(x/8)%2===0)black=true;if(black)setBit(r,y,x)}return{raster:r,height:h}}{const b=$('#testPattern');if(b)b.onclick=()=>{const j=testPattern();submitRaster(j.raster,j.height,'#printerMsg')}};
function applyQuery(){let mode=(params.get('mode')||'text').toLowerCase();if(mode==='imge')mode='image';if(!['text','image','camera','qr','printer'].includes(mode))mode='text';showView(mode);const val=params.get('val');if(val!==null&&mode==='text')$('#textInput').value=val;if(val!==null&&mode==='qr')$('#qrInput').value=val;const d=params.get('dither'),th=params.get('threshold'),mh=params.get('maxHeight');if((mode==='image'||mode==='camera')){if(['threshold','bayer','floyd'].includes(d))$('#'+mode+'Dither').value=d;if(th!==null){const n=Math.max(32,Math.min(224,Number(th)||128));$('#'+mode+'Threshold').value=String(n);$('#'+mode+'ThresholdValue').textContent=String(n)}if(['512','1024','1600','2048'].includes(mh))$('#'+mode+'MaxHeight').value=mh}if(mode==='text'){const size=params.get('size'),align=params.get('align'),line=params.get('line'),bold=params.get('bold');if(['18','22','26','32','40','48'].includes(size))$('#textSize').value=size;if(['left','center','right'].includes(align))$('#textAlign').value=align;if(['1.15','1.3','1.5'].includes(line))$('#textLine').value=line;if(bold!==null)$('#textBold').checked=['1','true','yes','on'].includes(bold.toLowerCase())}}
async function boot(){applyQuery();renderText();renderQr();if(!window.isSecureContext||!navigator.bluetooth){$('#secureNotice').hidden=false;setState('#printerMsg','Web Bluetoothが利用できません。HTTPS + 対応ブラウザが必要です。',true)}else if(targetMac){setState('#printerMsg','Previously authorized devicesから自動接続を試しています…');const ok=await transport.tryAutoConnect();setState('#printerMsg',ok?'Connected automatically.':'自動接続対象が見つかりません。Connect Printerを押して選択してください。',false)}else setState('#printerMsg','Connect Printerを押してプリンターを選択してください。');refreshPrintButtons()}
boot().catch(e=>{log('boot error',e.stack||e);setState('#printerMsg',e.message||String(e),true)});
